### ISSUE TITLE
Thread safety of fpta_table_clear

### ISSUE THREAD

**Issue by leisim** [erthink/libfpta#22]
Is `fpta_table_clear` thread safe?

It [uses](https://github.com/erthink/libfpta/blob/1470be46196dd6e7a65970db45436cf29dedfc36/src/table.cxx#L433) `mdbx_drop` which is documented to not be thread-safe. I don't see any mutex protecting the call.

**Comment by erthink** [comment]
None of data modify methods/functions are thread safety.
But all of ones executes within a write-transaction that hold the global (single for a DB instance) shared mutex.
This is fundamental concept of MDBX.

**Comment by leisim** [comment]
But the write txns can run in parallel with read txns right? Won't `mdbx_drop` cause read operations the the same db to fail? Maybe I misunderstood the documentation...

**Comment by erthink** [comment]
Seems you are missed reading about some basic things like MVCC.
I recommend to read any deep review of the LMDB internals.

However, historically there are some drawbacks working with dbi-handles inside a single multithreaded process.
In general, all the problems are due to the fact that dbi-handles have global visibility inside the process, without arranging to the history axis of MVCC snapshots. For instance:
1.`mdbx_drop()` called within one threads that executes a write transaction may invalidate the dbi-handle which may be simultaneously used by other thread(s) that executes a read transaction(s).
2. Some thread started a new/fresh read transaction may see that a named subDB correspond to a some dbi-handle was dropped by other process.This will invalidates such dbi-handle for other thread(s) in this process, includes ones with previously started read transaction(s) which see a MVCC-snapshot(s) where noted named subDB still exists. 

So, _libfpta_ internally uses [`schema_rwlock`](https://github.com/erthink/libfpta/blob/e6f71b3c9b44330491e135314e752c70eadaeb90/src/details.h#L42) (for [alterable-schema](https://github.com/erthink/libfpta/blob/e6f71b3c9b44330491e135314e752c70eadaeb90/fast_positive/tables.h#L1166-L1180) cases) and [`FPTA_TARDY_DBI`](https://github.com/erthink/libfpta/blob/e6f71b3c9b44330491e135314e752c70eadaeb90/fast_positive/tables.h#L357-L358) to resolve described above collisions with a dbi-handles.

**Comment by leisim** [comment]
Thanks for the detailed explanation!
